### ISSUE TITLE
Error when starting Simulation II

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#173]
```
Version: 0.6.1
Move component 'OR' with ID 229 by mouse
Start creating junction of EdgeView
Create junction from EdgeView 182 to port of OR
Start creating junction of EdgeView
Create junction from EdgeView 168 to port of OR
Move segment of EdgeView 236
Copy component 'NOT' with ID 142
Preparing paste from clipboard
Paste component 'NOT' with ID 237
Move component 'NOT' with ID 237 by mouse
Move component 'NOT' with ID 237 by mouse
Start creating junction of EdgeView
Create junction from EdgeView 230 to port of NOT
Start creating new EdgeView at PortView
Connect output of NOT with input of Tri-State Buffer
Move component 'NOT' with ID 237 by mouse
Change property 'Orientation' of component 237 to 'South'
Move component 'NOT' with ID 237 by mouse
Open application data
Enter execution mode (deep = true)
ch.scorpion.jabbah.base.c.b: Illegal state: Port already connected
	at ch.scorpion.antares.c.b(SourceFile:3022)
	at ch.scorpion.jabbah.graph.model.port.PortImpl.connectTo(SourceFile:104)
	at ch.scorpion.jabbah.graph.model.d.f.resolve(SourceFile:157)
	at ch.scorpion.jabbah.e.j.a(SourceFile:71)
	at ch.scorpion.jabbah.e.j.a(SourceFile:60)
	at ch.scorpion.jabbah.e.t.a(SourceFile:63)
	at ch.scorpion.jabbah.e.o.a(SourceFile:31)
	at ch.scorpion.jabbah.e.a.a(SourceFile:43)
	at ch.scorpion.jabbah.e.a.a(SourceFile:28)
	at ch.scorpion.jabbah.graph.m.a(SourceFile:228)
	at ch.scorpion.jabbah.graph.model.f.r.a(SourceFile:226)
	at ch.scorpion.jabbah.graph.model.f.r.a(SourceFile:212)
	at ch.scorpion.jabbah.graph.model.b.a.a(SourceFile:147)
	at ch.scorpion.jabbah.graph.view.N.a(SourceFile:1093)
	at ch.scorpion.jabbah.graph.view.P.invoke(SourceFile:1045)
	at ch.scorpion.jabbah.base.b.a.b(SourceFile:73)
	at ch.scorpion.jabbah.d.e.o.b(SourceFile:1344)
	at ch.scorpion.jabbah.graph.a.k.invoke(SourceFile:1089)
	at ch.scorpion.jabbah.base.Q.run(SourceFile:22)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by richardabendroth** [comment]
```
Version: 0.6.1
Change property 'Number of Inputs' of component 274 to '3'
Move component 'AND' with ID 274 by mouse
Start creating new EdgeView at PortView
Start creating junction of EdgeView
Create junction from EdgeView 267 to port of AND
Move segment of EdgeView 277
Move segment of EdgeView 267
Move segment of EdgeView 277
Move segment of EdgeView 254
Open application data
Copy 14 components
Preparing paste from clipboard
Paste 14 components
Move 14 components by mouse
Delete component 'Double Throw Switch' with ID 122
Delete component 'Double Throw Switch' with ID 115
Add Component 'Copy of Double Throw Switch' from library/project
Add Component 'Copy of Double Throw Switch' from library/project
Move component 'Copy of Double Throw Switch' with ID 123 by mouse
Enter execution mode (deep = true)
ch.scorpion.jabbah.base.c.b: Illegal state: Port already connected
	at ch.scorpion.antares.c.b(SourceFile:3022)
	at ch.scorpion.jabbah.graph.model.port.PortImpl.connectTo(SourceFile:104)
	at ch.scorpion.jabbah.graph.model.d.f.resolve(SourceFile:157)
	at ch.scorpion.jabbah.e.j.a(SourceFile:71)
	at ch.scorpion.jabbah.e.j.a(SourceFile:60)
	at ch.scorpion.jabbah.e.t.a(SourceFile:63)
	at ch.scorpion.jabbah.e.o.a(SourceFile:31)
	at ch.scorpion.jabbah.e.a.a(SourceFile:43)
	at ch.scorpion.jabbah.e.a.a(SourceFile:28)
	at ch.scorpion.jabbah.graph.m.a(SourceFile:228)
	at ch.scorpion.jabbah.graph.model.f.r.a(SourceFile:226)
	at ch.scorpion.jabbah.graph.model.f.r.a(SourceFile:212)
	at ch.scorpion.jabbah.graph.model.b.a.a(SourceFile:147)
	at ch.scorpion.jabbah.graph.view.N.a(SourceFile:1093)
	at ch.scorpion.jabbah.graph.view.P.invoke(SourceFile:1045)
	at ch.scorpion.jabbah.base.b.a.b(SourceFile:73)
	at ch.scorpion.jabbah.d.e.o.b(SourceFile:1344)
	at ch.scorpion.jabbah.graph.a.k.invoke(SourceFile:1089)
	at ch.scorpion.jabbah.base.Q.run(SourceFile:22)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by richardabendroth** [comment]
This happened after deleting a Component that had been connected at all its ports and replacing it with a copy of that component (to test an alternative implementation).
