### ISSUE TITLE
Error when starting simulation

### ISSUE THREAD

**Issue by p-** [flandreas/antares#42]
Hi @flandreas 

Very nice progress in Antares 0.3.0, congrats!

So I played around with Antares 0.3.0 and following exception occured, when I clicked on the yellow highlighted part of the imported Tannenbaum project (looks very neat btw!):

![antares-micro-ex](https://user-images.githubusercontent.com/176818/105574946-c860de80-5d5f-11eb-9651-55e0e68e6f04.png)

```
2021-01-23 09:05:53,161 ERROR [AWT-EventQueue-0] (SourceFile:26) - Unexpected error: null
  java.util.ConcurrentModificationException
	  at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	  at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	  at ch.scorpion.jabbah.c.b.a.update(SourceFile:196)
	  at ch.scorpion.antares.view.input.SwitchView.updateLabels(SourceFile:413)
	  at ch.scorpion.antares.view.input.SwitchView.modelExchanged(SourceFile:148)
	  at ch.scorpion.antares.view.input.SwitchView.modelExchanged(SourceFile:59)
	  at ch.scorpion.jabbah.graph.view.AbstractGraphElementView.setModel(SourceFile:41)
	  at ch.scorpion.antares.view.input.SwitchView.bindToModel(SourceFile:321)
	  at ch.scorpion.antares.view.input.SwitchView.bindToModel(SourceFile:59)
	  at ch.scorpion.jabbah.graph.container.ControlViewComponent.bindToGraph(SourceFile:172)
	  at ch.scorpion.jabbah.graph.view.vertice.SubGraphVerticeViewImpl.bind(SourceFile:316)
	  at ch.scorpion.jabbah.graph.view.graph.GraphViewImpl.bind(SourceFile:151)
	  at ch.scorpion.jabbah.graph.g.aE.a(SourceFile:5216)
	  at ch.scorpion.jabbah.graph.g.aU.invoke(SourceFile:1105)
	  at ch.scorpion.jabbah.base.b.a.b(SourceFile:73)
	  at ch.scorpion.jabbah.d.e.o.b(SourceFile:1348)
	  at ch.scorpion.jabbah.graph.g.a.l.invoke(SourceFile:1195)
	  at ch.scorpion.jabbah.base.Q.run(SourceFile:22)
	  at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	  at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	  at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	  at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	  at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	  at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	  at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	  at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	  at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	  at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

I couldn't reproduce this error and I don't think it's very important. But the dialog told me to report it ;)

Cheers

**Comment by flandreas** [comment]
Hi @p- 

I'm glad you enjoy the new release. Thank you for reporting this. I was able to reproduce it by selecting the control console component and then starting the simulation. I will try to fix this with the next release.
