### ISSUE TITLE
Unexpected Error after Deleting a Sub-circuit

### ISSUE THREAD

**Issue by LuminousXLB** [flandreas/antares#577]
This happens after 
- Build a circuit C1
- Build another circuit C2, where C1 is a building block of C2
- Delete C1
- Open C2

I recommend detect the dependency before deleting a circuit, or give a proper error prompt when a component is not available.

```
Version: 1.4.0
Loading settings from 'C:\Users\xxx\AppData\Roaming\Antares\Antares.ini'
Loading preferences from 'C:\Users\xxx\AppData\Roaming\Antares\Antares.pref'
Setting DrawingView with 'New Circuit' to editable=true
Setting DrawingView with 'Symbol' to editable=true
Setting DrawingView with 'Symbol' to editable=true
Setting DrawingView with 'New Circuit' to editable=true
Setting DrawingView with 'New Circuit' to editable=true
Setting DrawingView with 'Symbol' to editable=true
Setting DrawingView with 'Symbol' to editable=true
Setting DrawingView with 'New Circuit' to editable=true
Setting DrawingView with 'New Circuit' to editable=true
Setting DrawingView with 'Symbol' to editable=true
Setting DrawingView with 'Symbol' to editable=true
Setting DrawingView with '1b' to editable=true
Setting DrawingView with '1b' to editable=true
java.lang.NullPointerException
	at ch.scorpion.jabbah.graph.library.aB.j(SourceFile:133)
	at ch.scorpion.jabbah.graph.library.aB.c(SourceFile:127)
	at ch.scorpion.jabbah.graph.library.az.c(SourceFile:41)
	at ch.scorpion.jabbah.graph.model.f.l.k(SourceFile:322)
	at ch.scorpion.jabbah.graph.model.f.l.a(SourceFile:314)
	at ch.scorpion.jabbah.graph.view.vertice.SubGraphVerticeViewImpl.getGraph(SourceFile:572)
	at ch.scorpion.jabbah.graph.view.vertice.SubGraphVerticeViewImpl.getDescribingName(SourceFile:501)
	at ch.scorpion.jabbah.graph.f.e.f$a.getTreeCellRendererComponent(SourceFile:60)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(Unknown Source)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(Unknown Source)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(Unknown Source)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(Unknown Source)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(Unknown Source)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(Unknown Source)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(Unknown Source)
	at java.desktop/javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(Unknown Source)
	at java.desktop/javax.swing.tree.DefaultTreeModel.reload(Unknown Source)
	at ch.scorpion.jabbah.base.swing.a.d.a(SourceFile:32)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by LuminousXLB** [comment]
Duplicate with #572
