### ISSUE TITLE
Cannot import SN 74xx.acl

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#596]
When trying to import the "SN 74xx.acl" from the git repo via File > Libraries > Import, an error message appears: 
![image](https://github.com/flandreas/antares/assets/25486087/40151075-3a17-4677-b645-df1fbfb7dde8)

**Comment by flandreas** [comment]
The problem was the broken download link. I could reproduce the problem when I tried to download the file GitHubs code tree. This downloaded some funny GitHub meta file of around 5 KB.

Clicking on the new "Library File" download link brings you to the following form:

<img width="930" alt="Screenshot 2023-06-29 at 08 08 00" src="https://github.com/flandreas/antares/assets/24633141/ff0573ab-9d29-46c1-9909-132db067bbaf">

Click here on the "Download" button to download the file. The downloaded file should be 52.6 KB.

**Comment by richardabendroth** [comment]
Still doesn't work, same error. Here is the file props dialog: 
![image](https://github.com/flandreas/antares/assets/25486087/37d28c6d-880c-44c2-9d37-1ec192ac696b)
Maybe a problem on Windows?

**Comment by flandreas** [comment]
I've just tested on my Windows machine successfully. The props dialog of the file looks exactly the same as yours.

Strange. What does the log file say?

**Comment by richardabendroth** [comment]
<pre>
2023-06-29 13:38:08,099  INFO [AWT-EventQueue-0] (SourceFile:74) - Import library 'SN74xx', replace if UUID exists = false
2023-06-29 13:38:08,135 ERROR [AWT-EventQueue-0] (SourceFile:78) - Error while importing library
java.nio.file.NoSuchFileException: C:\Users\*************\AppData\Local\Temp\14119506337284493673\6409db98-d3bb-474a-ba90-f5b9360009fa -> C:\Users\ra\AppData\Roaming\Antares\libraries\6409db98-d3bb-474a-ba90-f5b9360009fa
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.base/java.nio.file.Files.move(Unknown Source)
	at ch.scorpion.jabbah.graph.library.ab.a(SourceFile:37)
	at ch.scorpion.jabbah.graph.library.o.a(SourceFile:56)
	at ch.scorpion.jabbah.graph.library.ac.importLibrary(SourceFile:1182)
	at ch.scorpion.jabbah.graph.library.bB.a(SourceFile:376)
	at ch.scorpion.jabbah.graph.library.r.a(SourceFile:62)
	at ch.scorpion.jabbah.graph.library.j.e(SourceFile:75)
	at ch.scorpion.jabbah.graph.library.v$c.a(SourceFile:83)
	at ch.scorpion.jabbah.base.j.actionPerformed(SourceFile:74)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at ch.scorpion.jabbah.base.swing.c.d(SourceFile:105)
	at ch.scorpion.jabbah.graph.library.aW$b.a(SourceFile:51)
	at ch.scorpion.jabbah.graph.library.ch.a(SourceFile:25)
	at ch.scorpion.jabbah.base.j.actionPerformed(SourceFile:74)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
</pre>

**Comment by flandreas** [comment]
Thank you, Richard.

There is really a bug. It occurs if you haven't yet created any custom library, and the "library" directory in your project repository has not yet been created. I'll have to fix that.

As a workaround, do the following:
- First create a dummy custom library in File->Libraries
- Then import the SN74xx library file

I've just tested this on my Windows 11 machine where I also hadn't a custom library yet.
