### ISSUE TITLE
Error when deleting wire

### ISSUE THREAD

**Issue by richardabendroth** [flandreas/antares#640]
Version: 1.6.0
Move segment 0 of EdgeView 372
Move component 'D Flip-Flop' with ID 255 by mouse
Move component 'D Flip-Flop' with ID 255 by mouse
Move segment 1 of EdgeView 268
Move segment 1 of EdgeView 271
Move component 'D Flip-Flop' with ID 255 by mouse
Move segment 2 of EdgeView 268
Move segment 0 of EdgeView 268
Move segment 1 of EdgeView 271
Delete component with ID 271
Start creating new EdgeView at Port 2 of VerticeView 67
Max snapshot size reached. Create new snapshot.
Move component 'OR' with ID 282 by mouse
Move component 'D Flip-Flop' with ID 255 by mouse
Move segment 1 of EdgeView 447
Delete component with ID 447
Delete component with ID 447
Enter execution mode (deep = true)
Enter edit mode
Delete component with ID 447
java.lang.IllegalArgumentException: joined EdgeView is not adjacent
	at ch.scorpion.jabbah.graph.view.net.edge.B.a(SourceFile:57)
	at ch.scorpion.jabbah.graph.view.net.edge.EdgeViewImpl.join(SourceFile:606)
	at ch.scorpion.jabbah.graph.view.b.eA.a(SourceFile:218)
	at ch.scorpion.jabbah.graph.view.b.eA.a(SourceFile:46)
	at ch.scorpion.jabbah.graph.view.b.eA.e(SourceFile:87)
	at ch.scorpion.jabbah.graph.view.a.g.a(SourceFile:188)
	at ch.scorpion.jabbah.edit.c.d.a(SourceFile:176)
	at ch.scorpion.jabbah.graph.view.a.d.a(SourceFile:1164)
	at ch.scorpion.jabbah.edit.a.l$a.a(SourceFile:35)
	at ch.scorpion.jabbah.edit.a.j.a(SourceFile:41)
	at ch.scorpion.jabbah.base.j.actionPerformed(SourceFile:74)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyBinding(Unknown Source)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(Unknown Source)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(Unknown Source)
	at java.desktop/javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(Unknown Source)
	at java.desktop/javax.swing.JMenuBar.processKeyBinding(Unknown Source)
	at java.desktop/javax.swing.KeyboardManager.fireBinding(Unknown Source)
	at java.desktop/javax.swing.KeyboardManager.fireKeyboardAction(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyBindingsForAllComponents(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyBindings(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by flandreas** [comment]
@richardabendroth Thank you for reporting this, Richard.

What strikes me about the error log is the entry "Delete component with ID 447" occurring 3 times, without intermediate undo/redo log entries. The component is a wire. This might point to a deeper problem than just the "EdgeView is not adjacent", which is a geometry problem probably simple to solve.

Do you recall moving a segment of a wire near a D Flip-Flop or an OR gate and then deleting the wire? Didn't it go away, and you've tried again? Then you started and stopped the simulation, and then tried again to delete that wire?

Or didn't you notice any anomalies until the you deleted the wire and the unexpected error occurred?
